version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pentaledger_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pentaledger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/pentaledger/pentaledger-console:latest 
    container_name: pentaledger-console
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/pentaledger?sslmode=disable
    ports:
      - "3000:3000"

volumes:
  postgres_data: